service_name: travis-ci
# no repositorio do github em>settings>secrets and variables>Actions>New repository secret>Name: REPO_TOKEN Secret= token. Como isso é uma pipeline, através do actions conseguimos capturar qualquer variavel
repo_token: ${{ secrets.REPO_TOKEN }}