language: node_js
node_js: 
  # Vers達o do node. A vers達o esta dando erro
  # - 20
  # A vers達o 12 da problema com o react-router-dom@6.23.0
  # - 12
  - 16
# Script que tem que ser executado antes do antes do script "principal"
before_script:
# Pode ser usado npm ou yarn, escolhemos usar yarn.
  - yarn install
# Scripts que ir達o rodar quando buildar o projeto
script:
  - eslint 'src/**'
  - npm run test:ci