language: node_js
# versões disponiveis: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
node_js: 
# Podemos acompanhar todo processo de build pelos logs do travis de cada repo
  # Versão do node. A versão 18 a 20...22 esta dando erro com o travis na parte de instalação do node. Eles utilizam docker de fundo pra instalar a imagem do node
  # - 20
  # A versão 12 da problema com o react-router-dom@6.23.0
  # - 12
  # A versão 16 da problema com o @testing-library/react@15.0.6
  # - 16
  # A versão 17 da problema com o faker
  # - 17
  # Não consegui usar a latest, node
  - 17.9

# Esse addons é um macete quando você quer usar o cypress dentro do travisCi. libgconf-2-4 lib do Linux e precisa ter pra ele conseguir fazer o cypress funcionar dentro do Travis
addons:
  packages:
    - libgconf-2-4

install:
  - npm install

# Scripts que irão rodar quando buildar o projeto
script:
  # Pra pegar somente ts e tsx, se quiser pode fazer um eslint para todos src/**
  - eslint 'src/**/*.{ts,tsx}'
  # A diferença do test:coveralls para o test:ci. É que depois que fizer o build no travis e subir, ele vai gerar o coverage localmente e vai subir esse status para o coveralls
  - npm run test:coveralls
  - npm run test:cypress:ci